# Generated by Django 4.0.5 on 2022-06-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='MobileNo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Term',
            field=models.IntegerField(),
        ),
    ]
