# Generated by Django 4.0.5 on 2022-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0005_rename_name_account_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ID_card',
            new_name='ID_card_Front',
        ),
    ]
