# Generated by Django 4.0.5 on 2022-06-22 11:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_rename_id_card_account_id_card_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ID_card_Back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
