# Generated by Django 4.0.5 on 2022-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_account_id_card_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ID_card_Front',
            new_name='ID_card',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ID_card_Back',
        ),
        migrations.AlterField(
            model_name='account',
            name='Full_Name',
            field=models.CharField(max_length=100),
        ),
    ]
